#!/usr/bin/env bash

sudo cp vscode-url-handler.desktop /usr/share/applications
sudo update-desktop-database

sudo cp vscode-url-handler /usr/local/bin/
sudo chmod +x /usr/local/bin/vscode-url-handler
